version: '3'
services:
  # The Backed Server
  server:
    image: "963933760463.dkr.ecr.us-east-1.amazonaws.com/prod-redkite-backend"
    # build:
    #   context: ./
    #   dockerfile: local-server.dockerfile
    ports:
      - "3333:3333" 
    volumes:
      - backend-server:/app
    links:
      - kue
      - redis
      # - mysql

volumes:
  backend-server:
  backend-kue:
  backend-mysql:
  backend-redis:
